name: Close Pull Request

on:
  pull_request:
    types:
      - opened
    paths:
      - "Formula/*.rb"

concurrency:
  group: close-pr
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Delete
        env:
          HEAD_REF: ${{github.event.pull_request.head.ref}}
        run: git push origin --delete "$HEAD_REF"
